development:
  adapter: postgresql
  encoding: unicode
  database: status_rollup_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: status_rollup_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: status_rollup_production
  pool: 5
  username:
  password:
